#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChiTieu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbQuanLyChiTieu")]
	public partial class dbcsdlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbAccount(tbAccount instance);
    partial void UpdatetbAccount(tbAccount instance);
    partial void DeletetbAccount(tbAccount instance);
    partial void InserttbDienGiai(tbDienGiai instance);
    partial void UpdatetbDienGiai(tbDienGiai instance);
    partial void DeletetbDienGiai(tbDienGiai instance);
    partial void InserttbChiTieu(tbChiTieu instance);
    partial void UpdatetbChiTieu(tbChiTieu instance);
    partial void DeletetbChiTieu(tbChiTieu instance);
    partial void InserttbChiTieuChiTiet(tbChiTieuChiTiet instance);
    partial void UpdatetbChiTieuChiTiet(tbChiTieuChiTiet instance);
    partial void DeletetbChiTieuChiTiet(tbChiTieuChiTiet instance);
    partial void InserttbDanhMuc(tbDanhMuc instance);
    partial void UpdatetbDanhMuc(tbDanhMuc instance);
    partial void DeletetbDanhMuc(tbDanhMuc instance);
    #endregion
		
		public dbcsdlDataContext() : 
				base(global::QuanLyChiTieu.Properties.Settings.Default.dbQuanLyChiTieuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbAccount> tbAccounts
		{
			get
			{
				return this.GetTable<tbAccount>();
			}
		}
		
		public System.Data.Linq.Table<tbDienGiai> tbDienGiais
		{
			get
			{
				return this.GetTable<tbDienGiai>();
			}
		}
		
		public System.Data.Linq.Table<tbChiTieu> tbChiTieus
		{
			get
			{
				return this.GetTable<tbChiTieu>();
			}
		}
		
		public System.Data.Linq.Table<tbChiTieuChiTiet> tbChiTieuChiTiets
		{
			get
			{
				return this.GetTable<tbChiTieuChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbDanhMuc> tbDanhMucs
		{
			get
			{
				return this.GetTable<tbDanhMuc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbAccount")]
	public partial class tbAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _account_id;
		
		private string _account_username;
		
		private string _account_password;
		
		private string _account_fullname;
		
		private System.Nullable<System.DateTime> _account_createddate;
		
		private string _account_phonenumber;
		
		private string _account_email;
		
		private EntitySet<tbChiTieu> _tbChiTieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaccount_idChanging(int value);
    partial void Onaccount_idChanged();
    partial void Onaccount_usernameChanging(string value);
    partial void Onaccount_usernameChanged();
    partial void Onaccount_passwordChanging(string value);
    partial void Onaccount_passwordChanged();
    partial void Onaccount_fullnameChanging(string value);
    partial void Onaccount_fullnameChanged();
    partial void Onaccount_createddateChanging(System.Nullable<System.DateTime> value);
    partial void Onaccount_createddateChanged();
    partial void Onaccount_phonenumberChanging(string value);
    partial void Onaccount_phonenumberChanged();
    partial void Onaccount_emailChanging(string value);
    partial void Onaccount_emailChanged();
    #endregion
		
		public tbAccount()
		{
			this._tbChiTieus = new EntitySet<tbChiTieu>(new Action<tbChiTieu>(this.attach_tbChiTieus), new Action<tbChiTieu>(this.detach_tbChiTieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_username", DbType="NVarChar(MAX)")]
		public string account_username
		{
			get
			{
				return this._account_username;
			}
			set
			{
				if ((this._account_username != value))
				{
					this.Onaccount_usernameChanging(value);
					this.SendPropertyChanging();
					this._account_username = value;
					this.SendPropertyChanged("account_username");
					this.Onaccount_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_password", DbType="NVarChar(MAX)")]
		public string account_password
		{
			get
			{
				return this._account_password;
			}
			set
			{
				if ((this._account_password != value))
				{
					this.Onaccount_passwordChanging(value);
					this.SendPropertyChanging();
					this._account_password = value;
					this.SendPropertyChanged("account_password");
					this.Onaccount_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_fullname", DbType="NVarChar(MAX)")]
		public string account_fullname
		{
			get
			{
				return this._account_fullname;
			}
			set
			{
				if ((this._account_fullname != value))
				{
					this.Onaccount_fullnameChanging(value);
					this.SendPropertyChanging();
					this._account_fullname = value;
					this.SendPropertyChanged("account_fullname");
					this.Onaccount_fullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_createddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> account_createddate
		{
			get
			{
				return this._account_createddate;
			}
			set
			{
				if ((this._account_createddate != value))
				{
					this.Onaccount_createddateChanging(value);
					this.SendPropertyChanging();
					this._account_createddate = value;
					this.SendPropertyChanged("account_createddate");
					this.Onaccount_createddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_phonenumber", DbType="NVarChar(MAX)")]
		public string account_phonenumber
		{
			get
			{
				return this._account_phonenumber;
			}
			set
			{
				if ((this._account_phonenumber != value))
				{
					this.Onaccount_phonenumberChanging(value);
					this.SendPropertyChanging();
					this._account_phonenumber = value;
					this.SendPropertyChanged("account_phonenumber");
					this.Onaccount_phonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_email", DbType="NVarChar(MAX)")]
		public string account_email
		{
			get
			{
				return this._account_email;
			}
			set
			{
				if ((this._account_email != value))
				{
					this.Onaccount_emailChanging(value);
					this.SendPropertyChanging();
					this._account_email = value;
					this.SendPropertyChanged("account_email");
					this.Onaccount_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbAccount_tbChiTieu", Storage="_tbChiTieus", ThisKey="account_id", OtherKey="account_id")]
		public EntitySet<tbChiTieu> tbChiTieus
		{
			get
			{
				return this._tbChiTieus;
			}
			set
			{
				this._tbChiTieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbChiTieus(tbChiTieu entity)
		{
			this.SendPropertyChanging();
			entity.tbAccount = this;
		}
		
		private void detach_tbChiTieus(tbChiTieu entity)
		{
			this.SendPropertyChanging();
			entity.tbAccount = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDienGiai")]
	public partial class tbDienGiai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _diengiai_id;
		
		private string _diengiai_name;
		
		private System.Nullable<int> _danhmuc_id;
		
		private System.Nullable<long> _diengiai_price;
		
		private string _diengiai_note;
		
		private EntitySet<tbChiTieuChiTiet> _tbChiTieuChiTiets;
		
		private EntityRef<tbDanhMuc> _tbDanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondiengiai_idChanging(int value);
    partial void Ondiengiai_idChanged();
    partial void Ondiengiai_nameChanging(string value);
    partial void Ondiengiai_nameChanged();
    partial void Ondanhmuc_idChanging(System.Nullable<int> value);
    partial void Ondanhmuc_idChanged();
    partial void Ondiengiai_priceChanging(System.Nullable<long> value);
    partial void Ondiengiai_priceChanged();
    partial void Ondiengiai_noteChanging(string value);
    partial void Ondiengiai_noteChanged();
    #endregion
		
		public tbDienGiai()
		{
			this._tbChiTieuChiTiets = new EntitySet<tbChiTieuChiTiet>(new Action<tbChiTieuChiTiet>(this.attach_tbChiTieuChiTiets), new Action<tbChiTieuChiTiet>(this.detach_tbChiTieuChiTiets));
			this._tbDanhMuc = default(EntityRef<tbDanhMuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiai_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int diengiai_id
		{
			get
			{
				return this._diengiai_id;
			}
			set
			{
				if ((this._diengiai_id != value))
				{
					this.Ondiengiai_idChanging(value);
					this.SendPropertyChanging();
					this._diengiai_id = value;
					this.SendPropertyChanged("diengiai_id");
					this.Ondiengiai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiai_name", DbType="NVarChar(MAX)")]
		public string diengiai_name
		{
			get
			{
				return this._diengiai_name;
			}
			set
			{
				if ((this._diengiai_name != value))
				{
					this.Ondiengiai_nameChanging(value);
					this.SendPropertyChanging();
					this._diengiai_name = value;
					this.SendPropertyChanged("diengiai_name");
					this.Ondiengiai_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhmuc_id", DbType="Int")]
		public System.Nullable<int> danhmuc_id
		{
			get
			{
				return this._danhmuc_id;
			}
			set
			{
				if ((this._danhmuc_id != value))
				{
					if (this._tbDanhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondanhmuc_idChanging(value);
					this.SendPropertyChanging();
					this._danhmuc_id = value;
					this.SendPropertyChanged("danhmuc_id");
					this.Ondanhmuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiai_price", DbType="BigInt")]
		public System.Nullable<long> diengiai_price
		{
			get
			{
				return this._diengiai_price;
			}
			set
			{
				if ((this._diengiai_price != value))
				{
					this.Ondiengiai_priceChanging(value);
					this.SendPropertyChanging();
					this._diengiai_price = value;
					this.SendPropertyChanged("diengiai_price");
					this.Ondiengiai_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiai_note", DbType="NVarChar(MAX)")]
		public string diengiai_note
		{
			get
			{
				return this._diengiai_note;
			}
			set
			{
				if ((this._diengiai_note != value))
				{
					this.Ondiengiai_noteChanging(value);
					this.SendPropertyChanging();
					this._diengiai_note = value;
					this.SendPropertyChanged("diengiai_note");
					this.Ondiengiai_noteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbDienGiai_tbChiTieuChiTiet", Storage="_tbChiTieuChiTiets", ThisKey="diengiai_id", OtherKey="diengiai_id")]
		public EntitySet<tbChiTieuChiTiet> tbChiTieuChiTiets
		{
			get
			{
				return this._tbChiTieuChiTiets;
			}
			set
			{
				this._tbChiTieuChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbDanhMuc_tbDienGiai", Storage="_tbDanhMuc", ThisKey="danhmuc_id", OtherKey="danhmuc_id", IsForeignKey=true)]
		public tbDanhMuc tbDanhMuc
		{
			get
			{
				return this._tbDanhMuc.Entity;
			}
			set
			{
				tbDanhMuc previousValue = this._tbDanhMuc.Entity;
				if (((previousValue != value) 
							|| (this._tbDanhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbDanhMuc.Entity = null;
						previousValue.tbDienGiais.Remove(this);
					}
					this._tbDanhMuc.Entity = value;
					if ((value != null))
					{
						value.tbDienGiais.Add(this);
						this._danhmuc_id = value.danhmuc_id;
					}
					else
					{
						this._danhmuc_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbDanhMuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbChiTieuChiTiets(tbChiTieuChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbDienGiai = this;
		}
		
		private void detach_tbChiTieuChiTiets(tbChiTieuChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbDienGiai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbChiTieu")]
	public partial class tbChiTieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chitieu_id;
		
		private System.Nullable<int> _account_id;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private EntitySet<tbChiTieuChiTiet> _tbChiTieuChiTiets;
		
		private EntityRef<tbAccount> _tbAccount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchitieu_idChanging(int value);
    partial void Onchitieu_idChanged();
    partial void Onaccount_idChanging(System.Nullable<int> value);
    partial void Onaccount_idChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    #endregion
		
		public tbChiTieu()
		{
			this._tbChiTieuChiTiets = new EntitySet<tbChiTieuChiTiet>(new Action<tbChiTieuChiTiet>(this.attach_tbChiTieuChiTiets), new Action<tbChiTieuChiTiet>(this.detach_tbChiTieuChiTiets));
			this._tbAccount = default(EntityRef<tbAccount>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitieu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chitieu_id
		{
			get
			{
				return this._chitieu_id;
			}
			set
			{
				if ((this._chitieu_id != value))
				{
					this.Onchitieu_idChanging(value);
					this.SendPropertyChanging();
					this._chitieu_id = value;
					this.SendPropertyChanged("chitieu_id");
					this.Onchitieu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int")]
		public System.Nullable<int> account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					if (this._tbAccount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="Date")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbChiTieu_tbChiTieuChiTiet", Storage="_tbChiTieuChiTiets", ThisKey="chitieu_id", OtherKey="chitieu_id")]
		public EntitySet<tbChiTieuChiTiet> tbChiTieuChiTiets
		{
			get
			{
				return this._tbChiTieuChiTiets;
			}
			set
			{
				this._tbChiTieuChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbAccount_tbChiTieu", Storage="_tbAccount", ThisKey="account_id", OtherKey="account_id", IsForeignKey=true)]
		public tbAccount tbAccount
		{
			get
			{
				return this._tbAccount.Entity;
			}
			set
			{
				tbAccount previousValue = this._tbAccount.Entity;
				if (((previousValue != value) 
							|| (this._tbAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbAccount.Entity = null;
						previousValue.tbChiTieus.Remove(this);
					}
					this._tbAccount.Entity = value;
					if ((value != null))
					{
						value.tbChiTieus.Add(this);
						this._account_id = value.account_id;
					}
					else
					{
						this._account_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbAccount");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbChiTieuChiTiets(tbChiTieuChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbChiTieu = this;
		}
		
		private void detach_tbChiTieuChiTiets(tbChiTieuChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbChiTieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbChiTieuChiTiet")]
	public partial class tbChiTieuChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chitieuchitiet_id;
		
		private System.Nullable<int> _chitieu_id;
		
		private System.Nullable<int> _diengiai_id;
		
		private EntityRef<tbChiTieu> _tbChiTieu;
		
		private EntityRef<tbDienGiai> _tbDienGiai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchitieuchitiet_idChanging(int value);
    partial void Onchitieuchitiet_idChanged();
    partial void Onchitieu_idChanging(System.Nullable<int> value);
    partial void Onchitieu_idChanged();
    partial void Ondiengiai_idChanging(System.Nullable<int> value);
    partial void Ondiengiai_idChanged();
    #endregion
		
		public tbChiTieuChiTiet()
		{
			this._tbChiTieu = default(EntityRef<tbChiTieu>);
			this._tbDienGiai = default(EntityRef<tbDienGiai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitieuchitiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chitieuchitiet_id
		{
			get
			{
				return this._chitieuchitiet_id;
			}
			set
			{
				if ((this._chitieuchitiet_id != value))
				{
					this.Onchitieuchitiet_idChanging(value);
					this.SendPropertyChanging();
					this._chitieuchitiet_id = value;
					this.SendPropertyChanged("chitieuchitiet_id");
					this.Onchitieuchitiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chitieu_id", DbType="Int")]
		public System.Nullable<int> chitieu_id
		{
			get
			{
				return this._chitieu_id;
			}
			set
			{
				if ((this._chitieu_id != value))
				{
					if (this._tbChiTieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onchitieu_idChanging(value);
					this.SendPropertyChanging();
					this._chitieu_id = value;
					this.SendPropertyChanged("chitieu_id");
					this.Onchitieu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiai_id", DbType="Int")]
		public System.Nullable<int> diengiai_id
		{
			get
			{
				return this._diengiai_id;
			}
			set
			{
				if ((this._diengiai_id != value))
				{
					if (this._tbDienGiai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondiengiai_idChanging(value);
					this.SendPropertyChanging();
					this._diengiai_id = value;
					this.SendPropertyChanged("diengiai_id");
					this.Ondiengiai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbChiTieu_tbChiTieuChiTiet", Storage="_tbChiTieu", ThisKey="chitieu_id", OtherKey="chitieu_id", IsForeignKey=true)]
		public tbChiTieu tbChiTieu
		{
			get
			{
				return this._tbChiTieu.Entity;
			}
			set
			{
				tbChiTieu previousValue = this._tbChiTieu.Entity;
				if (((previousValue != value) 
							|| (this._tbChiTieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbChiTieu.Entity = null;
						previousValue.tbChiTieuChiTiets.Remove(this);
					}
					this._tbChiTieu.Entity = value;
					if ((value != null))
					{
						value.tbChiTieuChiTiets.Add(this);
						this._chitieu_id = value.chitieu_id;
					}
					else
					{
						this._chitieu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbChiTieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbDienGiai_tbChiTieuChiTiet", Storage="_tbDienGiai", ThisKey="diengiai_id", OtherKey="diengiai_id", IsForeignKey=true)]
		public tbDienGiai tbDienGiai
		{
			get
			{
				return this._tbDienGiai.Entity;
			}
			set
			{
				tbDienGiai previousValue = this._tbDienGiai.Entity;
				if (((previousValue != value) 
							|| (this._tbDienGiai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbDienGiai.Entity = null;
						previousValue.tbChiTieuChiTiets.Remove(this);
					}
					this._tbDienGiai.Entity = value;
					if ((value != null))
					{
						value.tbChiTieuChiTiets.Add(this);
						this._diengiai_id = value.diengiai_id;
					}
					else
					{
						this._diengiai_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbDienGiai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDanhMuc")]
	public partial class tbDanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _danhmuc_id;
		
		private string _danhmuc_name;
		
		private System.Nullable<int> _account_id;
		
		private EntitySet<tbDienGiai> _tbDienGiais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondanhmuc_idChanging(int value);
    partial void Ondanhmuc_idChanged();
    partial void Ondanhmuc_nameChanging(string value);
    partial void Ondanhmuc_nameChanged();
    partial void Onaccount_idChanging(System.Nullable<int> value);
    partial void Onaccount_idChanged();
    #endregion
		
		public tbDanhMuc()
		{
			this._tbDienGiais = new EntitySet<tbDienGiai>(new Action<tbDienGiai>(this.attach_tbDienGiais), new Action<tbDienGiai>(this.detach_tbDienGiais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhmuc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int danhmuc_id
		{
			get
			{
				return this._danhmuc_id;
			}
			set
			{
				if ((this._danhmuc_id != value))
				{
					this.Ondanhmuc_idChanging(value);
					this.SendPropertyChanging();
					this._danhmuc_id = value;
					this.SendPropertyChanged("danhmuc_id");
					this.Ondanhmuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhmuc_name", DbType="NVarChar(MAX)")]
		public string danhmuc_name
		{
			get
			{
				return this._danhmuc_name;
			}
			set
			{
				if ((this._danhmuc_name != value))
				{
					this.Ondanhmuc_nameChanging(value);
					this.SendPropertyChanging();
					this._danhmuc_name = value;
					this.SendPropertyChanged("danhmuc_name");
					this.Ondanhmuc_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_id", DbType="Int")]
		public System.Nullable<int> account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				if ((this._account_id != value))
				{
					this.Onaccount_idChanging(value);
					this.SendPropertyChanging();
					this._account_id = value;
					this.SendPropertyChanged("account_id");
					this.Onaccount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbDanhMuc_tbDienGiai", Storage="_tbDienGiais", ThisKey="danhmuc_id", OtherKey="danhmuc_id")]
		public EntitySet<tbDienGiai> tbDienGiais
		{
			get
			{
				return this._tbDienGiais;
			}
			set
			{
				this._tbDienGiais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDienGiais(tbDienGiai entity)
		{
			this.SendPropertyChanging();
			entity.tbDanhMuc = this;
		}
		
		private void detach_tbDienGiais(tbDienGiai entity)
		{
			this.SendPropertyChanging();
			entity.tbDanhMuc = null;
		}
	}
}
#pragma warning restore 1591
